// GENERATED by vgi.codegen.go_registry. DO NOT EDIT BY HAND.
//
// Generator: python -m vgi.codegen.go_registry v1
// Content hash: 103adb1b7979
//
// To regenerate:
//   uv run --project ~/Development/vgi-python python scripts/regen_generated.py

// Copyright 2025, 2026 Query Farm LLC - https://query.farm

package vgi

import (
	"context"

	"github.com/Query-farm/vgi-go/vgi/generated"
	"github.com/Query-farm/vgi-rpc-go/vgirpc"
	"github.com/apache/arrow-go/v18/arrow"
)

// vgiRequestParamsSchema is the params schema of every method that carries one
// packed record: a single `request` column holding the record's IPC.
// vgi-rpc-go unwraps it into the record struct, whose fields describe the
// inner batch; VgiRpcParamsSchema advertises this instead of those fields, or
// a client that builds its request from the advertised schema (the TypeScript
// client does) would find none of its keys and send all-nulls.
var vgiRequestParamsSchema = arrow.NewSchema([]arrow.Field{
	arrow.Field{Name: "request", Type: arrow.BinaryTypes.Binary},
}, nil)

// vgiInitHeaderSchema is the header of the vgi.v2 init stream
// (GlobalInitResponse).
var vgiInitHeaderSchema = arrow.NewSchema([]arrow.Field{
	arrow.Field{Name: "execution_id", Type: arrow.BinaryTypes.Binary},
	arrow.Field{Name: "opaque_data", Type: arrow.BinaryTypes.Binary, Nullable: true},
	arrow.Field{Name: "max_workers", Type: arrow.PrimitiveTypes.Int64},
}, nil)

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_bind: one `request` column; vgi-rpc-go unwraps it into
// AggregateBindRequestWire's fields.
func (AggregateBindRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_combine: one `request` column; vgi-rpc-go unwraps it into
// AggregateCombineRequestWire's fields.
func (AggregateCombineRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_destructor: one `request` column; vgi-rpc-go unwraps it into
// AggregateDestructorRequestWire's fields.
func (AggregateDestructorRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_finalize: one `request` column; vgi-rpc-go unwraps it into
// AggregateFinalizeRequestWire's fields.
func (AggregateFinalizeRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_streaming_chunk: one `request` column; vgi-rpc-go unwraps it into
// AggregateStreamingChunkRequestWire's fields.
func (AggregateStreamingChunkRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_streaming_close: one `request` column; vgi-rpc-go unwraps it into
// AggregateStreamingCloseRequestWire's fields.
func (AggregateStreamingCloseRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_streaming_open: one `request` column; vgi-rpc-go unwraps it into
// AggregateStreamingOpenRequestWire's fields.
func (AggregateStreamingOpenRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_update: one `request` column; vgi-rpc-go unwraps it into
// AggregateUpdateRequestWire's fields.
func (AggregateUpdateRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_window_batch: one `request` column; vgi-rpc-go unwraps it into
// AggregateWindowBatchRequestWire's fields.
func (AggregateWindowBatchRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_window_destructor: one `request` column; vgi-rpc-go unwraps it
// into AggregateWindowDestructorRequestWire's fields.
func (AggregateWindowDestructorRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_window_init: one `request` column; vgi-rpc-go unwraps it into
// AggregateWindowInitRequestWire's fields.
func (AggregateWindowInitRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// aggregate_window: one `request` column; vgi-rpc-go unwraps it into
// AggregateWindowRequestWire's fields.
func (AggregateWindowRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2 bind: one
// `request` column; vgi-rpc-go unwraps it into BindRequestWire's fields.
func (BindRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// table_function_cardinality, table_function_statistics: one `request` column;
// vgi-rpc-go unwraps it into CardinalityRequestWire's fields.
func (CardinalityRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// catalog_attach: one `request` column; vgi-rpc-go unwraps it into
// CatalogAttachRequestWire's fields.
func (CatalogAttachRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// catalog_create: one `request` column; vgi-rpc-go unwraps it into
// CatalogCreateRequestWire's fields.
func (CatalogCreateRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// catalog_index_create: one `request` column; vgi-rpc-go unwraps it into
// IndexCreateRequestWire's fields.
func (IndexCreateRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2 init: one
// `request` column; vgi-rpc-go unwraps it into InitRequestWire's fields.
func (InitRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// catalog_macro_create: one `request` column; vgi-rpc-go unwraps it into
// MacroCreateRequestWire's fields.
func (MacroCreateRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// table_function_plan: one `request` column; vgi-rpc-go unwraps it into
// PlanRequestWire's fields.
func (PlanRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// table_buffering_combine: one `request` column; vgi-rpc-go unwraps it into
// TableBufferingCombineRequestWire's fields.
func (TableBufferingCombineRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// table_buffering_destructor: one `request` column; vgi-rpc-go unwraps it into
// TableBufferingDestructorRequestWire's fields.
func (TableBufferingDestructorRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// table_buffering_process: one `request` column; vgi-rpc-go unwraps it into
// TableBufferingProcessRequestWire's fields.
func (TableBufferingProcessRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// catalog_table_create: one `request` column; vgi-rpc-go unwraps it into
// TableCreateRequestWire's fields.
func (TableCreateRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// VgiRpcParamsSchema advertises the wrapped protocol shape of vgi.v2
// table_function_dynamic_to_string: one `request` column; vgi-rpc-go unwraps
// it into TableFunctionDynamicToStringRequestWire's fields.
func (TableFunctionDynamicToStringRequestWire) VgiRpcParamsSchema() *arrow.Schema {
	return vgiRequestParamsSchema
}

// CatalogCatalogsParams is the params of vgi.v2 catalog_catalogs: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogCatalogsParams struct{}

// CatalogContentsParams is the params of vgi.v2 catalog_contents: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogContentsParams struct {
	AttachOpaqueData []byte  `vgirpc:"attach_opaque_data"`
	IfNoneMatch      *string `vgirpc:"if_none_match"`
}

// CatalogCopyFromFormatsParams is the params of vgi.v2
// catalog_copy_from_formats: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogCopyFromFormatsParams struct {
	AttachOpaqueData      []byte  `vgirpc:"attach_opaque_data"`
	TransactionOpaqueData *[]byte `vgirpc:"transaction_opaque_data"`
}

// CatalogDetachParams is the params of vgi.v2 catalog_detach: one field per
// params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogDetachParams struct {
	AttachOpaqueData []byte `vgirpc:"attach_opaque_data"`
}

// CatalogDropParams is the params of vgi.v2 catalog_drop: one field per
// params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogDropParams struct {
	Name string `vgirpc:"name"`
}

// CatalogIndexDropParams is the params of vgi.v2 catalog_index_drop: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogIndexDropParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	Cascade               bool     `vgirpc:"cascade"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogIndexGetParams is the params of vgi.v2 catalog_index_get: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogIndexGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogMacroDropParams is the params of vgi.v2 catalog_macro_drop: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogMacroDropParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogMacroGetParams is the params of vgi.v2 catalog_macro_get: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogMacroGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemaContentsFunctionsParams is the params of vgi.v2
// catalog_schema_contents_functions: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogSchemaContentsFunctionsParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	Path                  []string `vgirpc:"path"`
	Type                  string   `vgirpc:"type,enum"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemaContentsIndexesParams is the params of vgi.v2
// catalog_schema_contents_indexes: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogSchemaContentsIndexesParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	Path                  []string `vgirpc:"path"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemaContentsMacrosParams is the params of vgi.v2
// catalog_schema_contents_macros: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogSchemaContentsMacrosParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	Path                  []string `vgirpc:"path"`
	Type                  string   `vgirpc:"type,enum"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemaContentsTablesParams is the params of vgi.v2
// catalog_schema_contents_tables: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogSchemaContentsTablesParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	Path                  []string `vgirpc:"path"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemaContentsViewsParams is the params of vgi.v2
// catalog_schema_contents_views: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogSchemaContentsViewsParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	Path                  []string `vgirpc:"path"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemaCreateParams is the params of vgi.v2 catalog_schema_create: one
// field per params-schema column, in order. vgi-rpc-go derives the advertised
// schema from these tags.
type CatalogSchemaCreateParams struct {
	AttachOpaqueData      []byte             `vgirpc:"attach_opaque_data"`
	Path                  []string           `vgirpc:"path"`
	OnConflict            string             `vgirpc:"on_conflict,enum"`
	Comment               *string            `vgirpc:"comment"`
	Tags                  *map[string]string `vgirpc:"tags"`
	TransactionOpaqueData *[]byte            `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemaDropParams is the params of vgi.v2 catalog_schema_drop: one
// field per params-schema column, in order. vgi-rpc-go derives the advertised
// schema from these tags.
type CatalogSchemaDropParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	Path                  []string `vgirpc:"path"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	Cascade               bool     `vgirpc:"cascade"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemaGetParams is the params of vgi.v2 catalog_schema_get: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogSchemaGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	Path                  []string `vgirpc:"path"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogSchemasParams is the params of vgi.v2 catalog_schemas: one field per
// params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogSchemasParams struct {
	AttachOpaqueData      []byte  `vgirpc:"attach_opaque_data"`
	TransactionOpaqueData *[]byte `vgirpc:"transaction_opaque_data"`
}

// CatalogTableColumnAddParams is the params of vgi.v2
// catalog_table_column_add: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableColumnAddParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnDefinition      []byte   `vgirpc:"column_definition"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	IfColumnNotExists     bool     `vgirpc:"if_column_not_exists"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableColumnCommentSetParams is the params of vgi.v2
// catalog_table_column_comment_set: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableColumnCommentSetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnName            string   `vgirpc:"column_name"`
	Comment               *string  `vgirpc:"comment"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableColumnDefaultDropParams is the params of vgi.v2
// catalog_table_column_default_drop: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableColumnDefaultDropParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnName            string   `vgirpc:"column_name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableColumnDefaultSetParams is the params of vgi.v2
// catalog_table_column_default_set: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableColumnDefaultSetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnName            string   `vgirpc:"column_name"`
	Expression            string   `vgirpc:"expression"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableColumnDropParams is the params of vgi.v2
// catalog_table_column_drop: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableColumnDropParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnName            string   `vgirpc:"column_name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	IfColumnExists        bool     `vgirpc:"if_column_exists"`
	Cascade               bool     `vgirpc:"cascade"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableColumnRenameParams is the params of vgi.v2
// catalog_table_column_rename: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableColumnRenameParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnName            string   `vgirpc:"column_name"`
	NewColumnName         string   `vgirpc:"new_column_name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableColumnStatisticsGetParams is the params of vgi.v2
// catalog_table_column_statistics_get: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableColumnStatisticsGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableColumnTypeChangeParams is the params of vgi.v2
// catalog_table_column_type_change: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableColumnTypeChangeParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnDefinition      []byte   `vgirpc:"column_definition"`
	Expression            *string  `vgirpc:"expression"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableCommentSetParams is the params of vgi.v2
// catalog_table_comment_set: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableCommentSetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	Comment               *string  `vgirpc:"comment"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableDeleteFunctionGetParams is the params of vgi.v2
// catalog_table_delete_function_get: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableDeleteFunctionGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableDropParams is the params of vgi.v2 catalog_table_drop: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogTableDropParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	Cascade               bool     `vgirpc:"cascade"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableGetParams is the params of vgi.v2 catalog_table_get: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogTableGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	AtUnit                *string  `vgirpc:"at_unit"`
	AtValue               *string  `vgirpc:"at_value"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableInsertFunctionGetParams is the params of vgi.v2
// catalog_table_insert_function_get: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableInsertFunctionGetParams struct {
	AttachOpaqueData           []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath                 []string `vgirpc:"schema_path"`
	Name                       string   `vgirpc:"name"`
	TransactionOpaqueData      *[]byte  `vgirpc:"transaction_opaque_data"`
	WritableBranchFunctionName *string  `vgirpc:"writable_branch_function_name"`
}

// CatalogTableNotNullDropParams is the params of vgi.v2
// catalog_table_not_null_drop: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableNotNullDropParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnName            string   `vgirpc:"column_name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableNotNullSetParams is the params of vgi.v2
// catalog_table_not_null_set: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableNotNullSetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	ColumnName            string   `vgirpc:"column_name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableRenameParams is the params of vgi.v2 catalog_table_rename: one
// field per params-schema column, in order. vgi-rpc-go derives the advertised
// schema from these tags.
type CatalogTableRenameParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	NewName               string   `vgirpc:"new_name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableScanBranchesGetParams is the params of vgi.v2
// catalog_table_scan_branches_get: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableScanBranchesGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	AtUnit                *string  `vgirpc:"at_unit"`
	AtValue               *string  `vgirpc:"at_value"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableScanFunctionGetParams is the params of vgi.v2
// catalog_table_scan_function_get: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableScanFunctionGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	AtUnit                *string  `vgirpc:"at_unit"`
	AtValue               *string  `vgirpc:"at_value"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTableUpdateFunctionGetParams is the params of vgi.v2
// catalog_table_update_function_get: one field per params-schema column, in
// order. vgi-rpc-go derives the advertised schema from these tags.
type CatalogTableUpdateFunctionGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogTransactionBeginParams is the params of vgi.v2
// catalog_transaction_begin: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTransactionBeginParams struct {
	AttachOpaqueData []byte `vgirpc:"attach_opaque_data"`
}

// CatalogTransactionCommitParams is the params of vgi.v2
// catalog_transaction_commit: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTransactionCommitParams struct {
	AttachOpaqueData      []byte `vgirpc:"attach_opaque_data"`
	TransactionOpaqueData []byte `vgirpc:"transaction_opaque_data"`
}

// CatalogTransactionRollbackParams is the params of vgi.v2
// catalog_transaction_rollback: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogTransactionRollbackParams struct {
	AttachOpaqueData      []byte `vgirpc:"attach_opaque_data"`
	TransactionOpaqueData []byte `vgirpc:"transaction_opaque_data"`
}

// CatalogVersionParams is the params of vgi.v2 catalog_version: one field per
// params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogVersionParams struct {
	AttachOpaqueData      []byte  `vgirpc:"attach_opaque_data"`
	TransactionOpaqueData *[]byte `vgirpc:"transaction_opaque_data"`
}

// CatalogViewCommentSetParams is the params of vgi.v2
// catalog_view_comment_set: one field per params-schema column, in order.
// vgi-rpc-go derives the advertised schema from these tags.
type CatalogViewCommentSetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	Comment               *string  `vgirpc:"comment"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogViewCreateParams is the params of vgi.v2 catalog_view_create: one
// field per params-schema column, in order. vgi-rpc-go derives the advertised
// schema from these tags.
type CatalogViewCreateParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	Definition            string   `vgirpc:"definition"`
	OnConflict            string   `vgirpc:"on_conflict,enum"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogViewDropParams is the params of vgi.v2 catalog_view_drop: one field
// per params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogViewDropParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	Cascade               bool     `vgirpc:"cascade"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogViewGetParams is the params of vgi.v2 catalog_view_get: one field per
// params-schema column, in order. vgi-rpc-go derives the advertised schema
// from these tags.
type CatalogViewGetParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// CatalogViewRenameParams is the params of vgi.v2 catalog_view_rename: one
// field per params-schema column, in order. vgi-rpc-go derives the advertised
// schema from these tags.
type CatalogViewRenameParams struct {
	AttachOpaqueData      []byte   `vgirpc:"attach_opaque_data"`
	SchemaPath            []string `vgirpc:"schema_path"`
	Name                  string   `vgirpc:"name"`
	NewName               string   `vgirpc:"new_name"`
	IgnoreNotFound        bool     `vgirpc:"ignore_not_found"`
	TransactionOpaqueData *[]byte  `vgirpc:"transaction_opaque_data"`
}

// vgiService is the vgi.v2 protocol: every method a VGI worker serves,
// generated from the reference (vgi.protocol.VgiProtocol in vgi-python).
//
// registerVgiService hosts every method, so vgi_rpc.Reflection.v1 reports the
// same vgi.v2 hash from every SDK: the params and result types below derive
// the reference's schemas exactly. The protocol is the unit of optionality --
// every method is registered whether or not this worker implements it. An
// implementation embeds unimplementedVgiService and defines the methods it
// serves; the rest answer UNIMPLEMENTED. Never change a signature here by
// hand: regenerate it, so the change comes from the protocol.
type vgiService interface {
	// AggregateBind is vgi.v2 aggregate_bind (unary). Bind an aggregate function,
	// return output schema and execution_id.
	AggregateBind(ctx context.Context, cc *vgirpc.CallContext, req AggregateBindRequestWire) (AggregateBindResponseWire, error)

	// AggregateCombine is vgi.v2 aggregate_combine (unary). Merge source states
	// into target states.
	AggregateCombine(ctx context.Context, cc *vgirpc.CallContext, req AggregateCombineRequestWire) (AggregateCombineResponseWire, error)

	// AggregateDestructor is vgi.v2 aggregate_destructor (unary). Best-effort
	// cleanup of aggregate states. Must not raise.
	AggregateDestructor(ctx context.Context, cc *vgirpc.CallContext, req AggregateDestructorRequestWire) (AggregateDestructorResponseWire, error)

	// AggregateFinalize is vgi.v2 aggregate_finalize (unary). Produce results for
	// a chunk of group_ids.
	AggregateFinalize(ctx context.Context, cc *vgirpc.CallContext, req AggregateFinalizeRequestWire) (AggregateFinalizeResponseWire, error)

	// AggregateStreamingChunk is vgi.v2 aggregate_streaming_chunk (unary). Process
	// one input chunk; returns one output row per input row.
	AggregateStreamingChunk(ctx context.Context, cc *vgirpc.CallContext, req AggregateStreamingChunkRequestWire) (AggregateStreamingChunkResponseWire, error)

	// AggregateStreamingClose is vgi.v2 aggregate_streaming_close (unary). End the
	// streaming session, free per-session state.
	AggregateStreamingClose(ctx context.Context, cc *vgirpc.CallContext, req AggregateStreamingCloseRequestWire) (AggregateStreamingCloseResponseWire, error)

	// AggregateStreamingOpen is vgi.v2 aggregate_streaming_open (unary). Start a
	// streaming-partitioned aggregate session.
	AggregateStreamingOpen(ctx context.Context, cc *vgirpc.CallContext, req AggregateStreamingOpenRequestWire) (AggregateStreamingOpenResponseWire, error)

	// AggregateUpdate is vgi.v2 aggregate_update (unary). Accumulate rows from a
	// DataChunk into per-group state.
	AggregateUpdate(ctx context.Context, cc *vgirpc.CallContext, req AggregateUpdateRequestWire) (AggregateUpdateResponseWire, error)

	// AggregateWindow is vgi.v2 aggregate_window (unary). Compute an aggregate
	// value for one output row of the window.
	AggregateWindow(ctx context.Context, cc *vgirpc.CallContext, req AggregateWindowRequestWire) (AggregateWindowResponseWire, error)

	// AggregateWindowBatch is vgi.v2 aggregate_window_batch (unary). Compute count
	// window output rows in one batched RPC.
	AggregateWindowBatch(ctx context.Context, cc *vgirpc.CallContext, req AggregateWindowBatchRequestWire) (AggregateWindowBatchResponseWire, error)

	// AggregateWindowDestructor is vgi.v2 aggregate_window_destructor (unary).
	// Evict a cached partition from storage.
	AggregateWindowDestructor(ctx context.Context, cc *vgirpc.CallContext, req AggregateWindowDestructorRequestWire) (AggregateWindowDestructorResponseWire, error)

	// AggregateWindowInit is vgi.v2 aggregate_window_init (unary). Ship a
	// partition to the worker for windowed aggregation.
	AggregateWindowInit(ctx context.Context, cc *vgirpc.CallContext, req AggregateWindowInitRequestWire) (AggregateWindowInitResponseWire, error)

	// Bind is vgi.v2 bind (unary). Resolve output schema and validate arguments.
	Bind(ctx context.Context, cc *vgirpc.CallContext, req BindRequestWire) (BindResponseWire, error)

	// CatalogAttach is vgi.v2 catalog_attach (unary). Attach to a catalog with
	// options.
	CatalogAttach(ctx context.Context, cc *vgirpc.CallContext, req CatalogAttachRequestWire) (generated.CatalogAttachResult, error)

	// CatalogCatalogs is vgi.v2 catalog_catalogs (unary). List available catalog
	// names.
	CatalogCatalogs(ctx context.Context, cc *vgirpc.CallContext, req CatalogCatalogsParams) (CatalogsResponseWire, error)

	// CatalogContents is vgi.v2 catalog_contents (unary). Return every schema and
	// all of its contents in one result.
	CatalogContents(ctx context.Context, cc *vgirpc.CallContext, req CatalogContentsParams) (generated.CatalogContentsResponse, error)

	// CatalogCopyFromFormats is vgi.v2 catalog_copy_from_formats (unary). List
	// custom COPY ... FROM formats advertised by this catalog.
	CatalogCopyFromFormats(ctx context.Context, cc *vgirpc.CallContext, req CatalogCopyFromFormatsParams) (ItemsResponseWire, error)

	// CatalogCreate is vgi.v2 catalog_create (unary). Create a new catalog.
	CatalogCreate(ctx context.Context, cc *vgirpc.CallContext, req CatalogCreateRequestWire) error

	// CatalogDetach is vgi.v2 catalog_detach (unary). Detach from a catalog.
	CatalogDetach(ctx context.Context, cc *vgirpc.CallContext, req CatalogDetachParams) error

	// CatalogDrop is vgi.v2 catalog_drop (unary). Drop a catalog.
	CatalogDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogDropParams) error

	// CatalogIndexCreate is vgi.v2 catalog_index_create (unary). Create a new
	// index.
	CatalogIndexCreate(ctx context.Context, cc *vgirpc.CallContext, req IndexCreateRequestWire) error

	// CatalogIndexDrop is vgi.v2 catalog_index_drop (unary). Drop an index.
	CatalogIndexDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogIndexDropParams) error

	// CatalogIndexGet is vgi.v2 catalog_index_get (unary). Get information about
	// an index. Returns 0 or 1 items.
	CatalogIndexGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogIndexGetParams) (ItemsResponseWire, error)

	// CatalogMacroCreate is vgi.v2 catalog_macro_create (unary). Create a new
	// macro.
	CatalogMacroCreate(ctx context.Context, cc *vgirpc.CallContext, req MacroCreateRequestWire) error

	// CatalogMacroDrop is vgi.v2 catalog_macro_drop (unary). Drop a macro.
	CatalogMacroDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogMacroDropParams) error

	// CatalogMacroGet is vgi.v2 catalog_macro_get (unary). Get information about a
	// macro. Returns 0 or 1 items.
	CatalogMacroGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogMacroGetParams) (ItemsResponseWire, error)

	// CatalogSchemaContentsFunctions is vgi.v2 catalog_schema_contents_functions
	// (unary). List functions in a schema (scalar or table).
	CatalogSchemaContentsFunctions(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemaContentsFunctionsParams) (ItemsResponseWire, error)

	// CatalogSchemaContentsIndexes is vgi.v2 catalog_schema_contents_indexes
	// (unary). List indexes in a schema.
	CatalogSchemaContentsIndexes(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemaContentsIndexesParams) (ItemsResponseWire, error)

	// CatalogSchemaContentsMacros is vgi.v2 catalog_schema_contents_macros
	// (unary). List macros in a schema (scalar or table).
	CatalogSchemaContentsMacros(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemaContentsMacrosParams) (ItemsResponseWire, error)

	// CatalogSchemaContentsTables is vgi.v2 catalog_schema_contents_tables
	// (unary). List tables in a schema.
	CatalogSchemaContentsTables(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemaContentsTablesParams) (ItemsResponseWire, error)

	// CatalogSchemaContentsViews is vgi.v2 catalog_schema_contents_views (unary).
	// List views in a schema.
	CatalogSchemaContentsViews(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemaContentsViewsParams) (ItemsResponseWire, error)

	// CatalogSchemaCreate is vgi.v2 catalog_schema_create (unary). Create a new
	// schema.
	CatalogSchemaCreate(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemaCreateParams) error

	// CatalogSchemaDrop is vgi.v2 catalog_schema_drop (unary). Drop a schema.
	CatalogSchemaDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemaDropParams) error

	// CatalogSchemaGet is vgi.v2 catalog_schema_get (unary). Get information about
	// a schema. Returns 0 or 1 items.
	CatalogSchemaGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemaGetParams) (ItemsResponseWire, error)

	// CatalogSchemas is vgi.v2 catalog_schemas (unary). List schemas in the
	// catalog.
	CatalogSchemas(ctx context.Context, cc *vgirpc.CallContext, req CatalogSchemasParams) (ItemsResponseWire, error)

	// CatalogTableColumnAdd is vgi.v2 catalog_table_column_add (unary). Add a new
	// column to a table.
	CatalogTableColumnAdd(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableColumnAddParams) error

	// CatalogTableColumnCommentSet is vgi.v2 catalog_table_column_comment_set
	// (unary). Set or clear the comment on a table column.
	CatalogTableColumnCommentSet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableColumnCommentSetParams) error

	// CatalogTableColumnDefaultDrop is vgi.v2 catalog_table_column_default_drop
	// (unary). Remove the default value from a column.
	CatalogTableColumnDefaultDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableColumnDefaultDropParams) error

	// CatalogTableColumnDefaultSet is vgi.v2 catalog_table_column_default_set
	// (unary). Set the default value expression for a column.
	CatalogTableColumnDefaultSet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableColumnDefaultSetParams) error

	// CatalogTableColumnDrop is vgi.v2 catalog_table_column_drop (unary). Drop a
	// column from a table.
	CatalogTableColumnDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableColumnDropParams) error

	// CatalogTableColumnRename is vgi.v2 catalog_table_column_rename (unary).
	// Rename a column.
	CatalogTableColumnRename(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableColumnRenameParams) error

	// CatalogTableColumnStatisticsGet is vgi.v2
	// catalog_table_column_statistics_get (unary). Get column statistics for a
	// table.
	CatalogTableColumnStatisticsGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableColumnStatisticsGetParams) (*[]byte, error)

	// CatalogTableColumnTypeChange is vgi.v2 catalog_table_column_type_change
	// (unary). Change the type of a column.
	CatalogTableColumnTypeChange(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableColumnTypeChangeParams) error

	// CatalogTableCommentSet is vgi.v2 catalog_table_comment_set (unary). Set or
	// clear the comment on a table.
	CatalogTableCommentSet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableCommentSetParams) error

	// CatalogTableCreate is vgi.v2 catalog_table_create (unary). Create a new
	// table.
	CatalogTableCreate(ctx context.Context, cc *vgirpc.CallContext, req TableCreateRequestWire) error

	// CatalogTableDeleteFunctionGet is vgi.v2 catalog_table_delete_function_get
	// (unary). Get the delete function for a table. Returns WriteFunctionResult as
	// IPC bytes.
	CatalogTableDeleteFunctionGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableDeleteFunctionGetParams) (TableScanFunctionGetResponseWire, error)

	// CatalogTableDrop is vgi.v2 catalog_table_drop (unary). Drop a table.
	CatalogTableDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableDropParams) error

	// CatalogTableGet is vgi.v2 catalog_table_get (unary). Get information about a
	// table. Returns 0 or 1 items.
	CatalogTableGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableGetParams) (ItemsResponseWire, error)

	// CatalogTableInsertFunctionGet is vgi.v2 catalog_table_insert_function_get
	// (unary). Get the insert function for a table. Returns WriteFunctionResult as
	// IPC bytes.
	CatalogTableInsertFunctionGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableInsertFunctionGetParams) (TableScanFunctionGetResponseWire, error)

	// CatalogTableNotNullDrop is vgi.v2 catalog_table_not_null_drop (unary).
	// Remove NOT NULL constraint from a column.
	CatalogTableNotNullDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableNotNullDropParams) error

	// CatalogTableNotNullSet is vgi.v2 catalog_table_not_null_set (unary). Add NOT
	// NULL constraint to a column.
	CatalogTableNotNullSet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableNotNullSetParams) error

	// CatalogTableRename is vgi.v2 catalog_table_rename (unary). Rename a table.
	CatalogTableRename(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableRenameParams) error

	// CatalogTableScanBranchesGet is vgi.v2 catalog_table_scan_branches_get
	// (unary). Get the list of scan branches for a multi-branch table. Returns
	// ScanBranchesResult as IPC bytes.
	CatalogTableScanBranchesGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableScanBranchesGetParams) (TableScanBranchesGetResponseWire, error)

	// CatalogTableScanFunctionGet is vgi.v2 catalog_table_scan_function_get
	// (unary). Get the scan function for a table. Returns ScanFunctionResult as
	// IPC bytes.
	CatalogTableScanFunctionGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableScanFunctionGetParams) (TableScanFunctionGetResponseWire, error)

	// CatalogTableUpdateFunctionGet is vgi.v2 catalog_table_update_function_get
	// (unary). Get the update function for a table. Returns WriteFunctionResult as
	// IPC bytes.
	CatalogTableUpdateFunctionGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogTableUpdateFunctionGetParams) (TableScanFunctionGetResponseWire, error)

	// CatalogTransactionBegin is vgi.v2 catalog_transaction_begin (unary). Begin a
	// new transaction.
	CatalogTransactionBegin(ctx context.Context, cc *vgirpc.CallContext, req CatalogTransactionBeginParams) (TransactionBeginResponseWire, error)

	// CatalogTransactionCommit is vgi.v2 catalog_transaction_commit (unary).
	// Commit a transaction.
	CatalogTransactionCommit(ctx context.Context, cc *vgirpc.CallContext, req CatalogTransactionCommitParams) error

	// CatalogTransactionRollback is vgi.v2 catalog_transaction_rollback (unary).
	// Rollback a transaction.
	CatalogTransactionRollback(ctx context.Context, cc *vgirpc.CallContext, req CatalogTransactionRollbackParams) error

	// CatalogVersion is vgi.v2 catalog_version (unary). Get the current catalog
	// version.
	CatalogVersion(ctx context.Context, cc *vgirpc.CallContext, req CatalogVersionParams) (CatalogVersionResponseWire, error)

	// CatalogViewCommentSet is vgi.v2 catalog_view_comment_set (unary). Set or
	// clear the comment on a view.
	CatalogViewCommentSet(ctx context.Context, cc *vgirpc.CallContext, req CatalogViewCommentSetParams) error

	// CatalogViewCreate is vgi.v2 catalog_view_create (unary). Create a new view.
	CatalogViewCreate(ctx context.Context, cc *vgirpc.CallContext, req CatalogViewCreateParams) error

	// CatalogViewDrop is vgi.v2 catalog_view_drop (unary). Drop a view.
	CatalogViewDrop(ctx context.Context, cc *vgirpc.CallContext, req CatalogViewDropParams) error

	// CatalogViewGet is vgi.v2 catalog_view_get (unary). Get information about a
	// view. Returns 0 or 1 items.
	CatalogViewGet(ctx context.Context, cc *vgirpc.CallContext, req CatalogViewGetParams) (ItemsResponseWire, error)

	// CatalogViewRename is vgi.v2 catalog_view_rename (unary). Rename a view.
	CatalogViewRename(ctx context.Context, cc *vgirpc.CallContext, req CatalogViewRenameParams) error

	// Init is vgi.v2 init (stream). Initialize a function execution and return a
	// processing stream.
	Init(ctx context.Context, cc *vgirpc.CallContext, req InitRequestWire) (*vgirpc.StreamResult, error)

	// TableBufferingCombine is vgi.v2 table_buffering_combine (unary).
	// Once-per-query end-of-input signal. Returns finalize_state_ids.
	TableBufferingCombine(ctx context.Context, cc *vgirpc.CallContext, req TableBufferingCombineRequestWire) (TableBufferingCombineResponseWire, error)

	// TableBufferingDestructor is vgi.v2 table_buffering_destructor (unary).
	// Best-effort end-of-query cleanup. Must not raise.
	TableBufferingDestructor(ctx context.Context, cc *vgirpc.CallContext, req TableBufferingDestructorRequestWire) (TableBufferingDestructorResponseWire, error)

	// TableBufferingProcess is vgi.v2 table_buffering_process (unary). Sink one
	// input batch; return the worker-chosen state_id.
	TableBufferingProcess(ctx context.Context, cc *vgirpc.CallContext, req TableBufferingProcessRequestWire) (TableBufferingProcessResponseWire, error)

	// TableFunctionCardinality is vgi.v2 table_function_cardinality (unary).
	// Estimate the cardinality of a table function's output.
	TableFunctionCardinality(ctx context.Context, cc *vgirpc.CallContext, req CardinalityRequestWire) (TableCardinality, error)

	// TableFunctionDynamicToString is vgi.v2 table_function_dynamic_to_string
	// (unary). Return user-defined diagnostics for EXPLAIN ANALYZE Extra Info.
	TableFunctionDynamicToString(ctx context.Context, cc *vgirpc.CallContext, req TableFunctionDynamicToStringRequestWire) (TableFunctionDynamicToStringResponseWire, error)

	// TableFunctionPlan is vgi.v2 table_function_plan (unary). Plan a
	// table-function scan into named, independently redeemable splits.
	TableFunctionPlan(ctx context.Context, cc *vgirpc.CallContext, req PlanRequestWire) (PlanResponseWire, error)

	// TableFunctionStatistics is vgi.v2 table_function_statistics (unary). Return
	// per-column statistics for a table function's output.
	TableFunctionStatistics(ctx context.Context, cc *vgirpc.CallContext, req CardinalityRequestWire) (*[]byte, error)
}

// unimplementedVgiService answers every vgi.v2 method with UNIMPLEMENTED /
// method_not_implemented ("<method> is not implemented by this worker"). Embed
// it in a vgiService and define the methods the worker serves.
type unimplementedVgiService struct{}

// AggregateBind answers UNIMPLEMENTED: vgi.v2 aggregate_bind is not
// implemented by this worker.
func (unimplementedVgiService) AggregateBind(context.Context, *vgirpc.CallContext, AggregateBindRequestWire) (AggregateBindResponseWire, error) {
	return AggregateBindResponseWire{}, methodNotImplemented("aggregate_bind")
}

// AggregateCombine answers UNIMPLEMENTED: vgi.v2 aggregate_combine is not
// implemented by this worker.
func (unimplementedVgiService) AggregateCombine(context.Context, *vgirpc.CallContext, AggregateCombineRequestWire) (AggregateCombineResponseWire, error) {
	return AggregateCombineResponseWire{}, methodNotImplemented("aggregate_combine")
}

// AggregateDestructor answers UNIMPLEMENTED: vgi.v2 aggregate_destructor is
// not implemented by this worker.
func (unimplementedVgiService) AggregateDestructor(context.Context, *vgirpc.CallContext, AggregateDestructorRequestWire) (AggregateDestructorResponseWire, error) {
	return AggregateDestructorResponseWire{}, methodNotImplemented("aggregate_destructor")
}

// AggregateFinalize answers UNIMPLEMENTED: vgi.v2 aggregate_finalize is not
// implemented by this worker.
func (unimplementedVgiService) AggregateFinalize(context.Context, *vgirpc.CallContext, AggregateFinalizeRequestWire) (AggregateFinalizeResponseWire, error) {
	return AggregateFinalizeResponseWire{}, methodNotImplemented("aggregate_finalize")
}

// AggregateStreamingChunk answers UNIMPLEMENTED: vgi.v2
// aggregate_streaming_chunk is not implemented by this worker.
func (unimplementedVgiService) AggregateStreamingChunk(context.Context, *vgirpc.CallContext, AggregateStreamingChunkRequestWire) (AggregateStreamingChunkResponseWire, error) {
	return AggregateStreamingChunkResponseWire{}, methodNotImplemented("aggregate_streaming_chunk")
}

// AggregateStreamingClose answers UNIMPLEMENTED: vgi.v2
// aggregate_streaming_close is not implemented by this worker.
func (unimplementedVgiService) AggregateStreamingClose(context.Context, *vgirpc.CallContext, AggregateStreamingCloseRequestWire) (AggregateStreamingCloseResponseWire, error) {
	return AggregateStreamingCloseResponseWire{}, methodNotImplemented("aggregate_streaming_close")
}

// AggregateStreamingOpen answers UNIMPLEMENTED: vgi.v2
// aggregate_streaming_open is not implemented by this worker.
func (unimplementedVgiService) AggregateStreamingOpen(context.Context, *vgirpc.CallContext, AggregateStreamingOpenRequestWire) (AggregateStreamingOpenResponseWire, error) {
	return AggregateStreamingOpenResponseWire{}, methodNotImplemented("aggregate_streaming_open")
}

// AggregateUpdate answers UNIMPLEMENTED: vgi.v2 aggregate_update is not
// implemented by this worker.
func (unimplementedVgiService) AggregateUpdate(context.Context, *vgirpc.CallContext, AggregateUpdateRequestWire) (AggregateUpdateResponseWire, error) {
	return AggregateUpdateResponseWire{}, methodNotImplemented("aggregate_update")
}

// AggregateWindow answers UNIMPLEMENTED: vgi.v2 aggregate_window is not
// implemented by this worker.
func (unimplementedVgiService) AggregateWindow(context.Context, *vgirpc.CallContext, AggregateWindowRequestWire) (AggregateWindowResponseWire, error) {
	return AggregateWindowResponseWire{}, methodNotImplemented("aggregate_window")
}

// AggregateWindowBatch answers UNIMPLEMENTED: vgi.v2 aggregate_window_batch is
// not implemented by this worker.
func (unimplementedVgiService) AggregateWindowBatch(context.Context, *vgirpc.CallContext, AggregateWindowBatchRequestWire) (AggregateWindowBatchResponseWire, error) {
	return AggregateWindowBatchResponseWire{}, methodNotImplemented("aggregate_window_batch")
}

// AggregateWindowDestructor answers UNIMPLEMENTED: vgi.v2
// aggregate_window_destructor is not implemented by this worker.
func (unimplementedVgiService) AggregateWindowDestructor(context.Context, *vgirpc.CallContext, AggregateWindowDestructorRequestWire) (AggregateWindowDestructorResponseWire, error) {
	return AggregateWindowDestructorResponseWire{}, methodNotImplemented("aggregate_window_destructor")
}

// AggregateWindowInit answers UNIMPLEMENTED: vgi.v2 aggregate_window_init is
// not implemented by this worker.
func (unimplementedVgiService) AggregateWindowInit(context.Context, *vgirpc.CallContext, AggregateWindowInitRequestWire) (AggregateWindowInitResponseWire, error) {
	return AggregateWindowInitResponseWire{}, methodNotImplemented("aggregate_window_init")
}

// Bind answers UNIMPLEMENTED: vgi.v2 bind is not implemented by this worker.
func (unimplementedVgiService) Bind(context.Context, *vgirpc.CallContext, BindRequestWire) (BindResponseWire, error) {
	return BindResponseWire{}, methodNotImplemented("bind")
}

// CatalogAttach answers UNIMPLEMENTED: vgi.v2 catalog_attach is not
// implemented by this worker.
func (unimplementedVgiService) CatalogAttach(context.Context, *vgirpc.CallContext, CatalogAttachRequestWire) (generated.CatalogAttachResult, error) {
	return generated.CatalogAttachResult{}, methodNotImplemented("catalog_attach")
}

// CatalogCatalogs answers UNIMPLEMENTED: vgi.v2 catalog_catalogs is not
// implemented by this worker.
func (unimplementedVgiService) CatalogCatalogs(context.Context, *vgirpc.CallContext, CatalogCatalogsParams) (CatalogsResponseWire, error) {
	return CatalogsResponseWire{}, methodNotImplemented("catalog_catalogs")
}

// CatalogContents answers UNIMPLEMENTED: vgi.v2 catalog_contents is not
// implemented by this worker.
func (unimplementedVgiService) CatalogContents(context.Context, *vgirpc.CallContext, CatalogContentsParams) (generated.CatalogContentsResponse, error) {
	return generated.CatalogContentsResponse{}, methodNotImplemented("catalog_contents")
}

// CatalogCopyFromFormats answers UNIMPLEMENTED: vgi.v2
// catalog_copy_from_formats is not implemented by this worker.
func (unimplementedVgiService) CatalogCopyFromFormats(context.Context, *vgirpc.CallContext, CatalogCopyFromFormatsParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_copy_from_formats")
}

// CatalogCreate answers UNIMPLEMENTED: vgi.v2 catalog_create is not
// implemented by this worker.
func (unimplementedVgiService) CatalogCreate(context.Context, *vgirpc.CallContext, CatalogCreateRequestWire) error {
	return methodNotImplemented("catalog_create")
}

// CatalogDetach answers UNIMPLEMENTED: vgi.v2 catalog_detach is not
// implemented by this worker.
func (unimplementedVgiService) CatalogDetach(context.Context, *vgirpc.CallContext, CatalogDetachParams) error {
	return methodNotImplemented("catalog_detach")
}

// CatalogDrop answers UNIMPLEMENTED: vgi.v2 catalog_drop is not implemented by
// this worker.
func (unimplementedVgiService) CatalogDrop(context.Context, *vgirpc.CallContext, CatalogDropParams) error {
	return methodNotImplemented("catalog_drop")
}

// CatalogIndexCreate answers UNIMPLEMENTED: vgi.v2 catalog_index_create is not
// implemented by this worker.
func (unimplementedVgiService) CatalogIndexCreate(context.Context, *vgirpc.CallContext, IndexCreateRequestWire) error {
	return methodNotImplemented("catalog_index_create")
}

// CatalogIndexDrop answers UNIMPLEMENTED: vgi.v2 catalog_index_drop is not
// implemented by this worker.
func (unimplementedVgiService) CatalogIndexDrop(context.Context, *vgirpc.CallContext, CatalogIndexDropParams) error {
	return methodNotImplemented("catalog_index_drop")
}

// CatalogIndexGet answers UNIMPLEMENTED: vgi.v2 catalog_index_get is not
// implemented by this worker.
func (unimplementedVgiService) CatalogIndexGet(context.Context, *vgirpc.CallContext, CatalogIndexGetParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_index_get")
}

// CatalogMacroCreate answers UNIMPLEMENTED: vgi.v2 catalog_macro_create is not
// implemented by this worker.
func (unimplementedVgiService) CatalogMacroCreate(context.Context, *vgirpc.CallContext, MacroCreateRequestWire) error {
	return methodNotImplemented("catalog_macro_create")
}

// CatalogMacroDrop answers UNIMPLEMENTED: vgi.v2 catalog_macro_drop is not
// implemented by this worker.
func (unimplementedVgiService) CatalogMacroDrop(context.Context, *vgirpc.CallContext, CatalogMacroDropParams) error {
	return methodNotImplemented("catalog_macro_drop")
}

// CatalogMacroGet answers UNIMPLEMENTED: vgi.v2 catalog_macro_get is not
// implemented by this worker.
func (unimplementedVgiService) CatalogMacroGet(context.Context, *vgirpc.CallContext, CatalogMacroGetParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_macro_get")
}

// CatalogSchemaContentsFunctions answers UNIMPLEMENTED: vgi.v2
// catalog_schema_contents_functions is not implemented by this worker.
func (unimplementedVgiService) CatalogSchemaContentsFunctions(context.Context, *vgirpc.CallContext, CatalogSchemaContentsFunctionsParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_schema_contents_functions")
}

// CatalogSchemaContentsIndexes answers UNIMPLEMENTED: vgi.v2
// catalog_schema_contents_indexes is not implemented by this worker.
func (unimplementedVgiService) CatalogSchemaContentsIndexes(context.Context, *vgirpc.CallContext, CatalogSchemaContentsIndexesParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_schema_contents_indexes")
}

// CatalogSchemaContentsMacros answers UNIMPLEMENTED: vgi.v2
// catalog_schema_contents_macros is not implemented by this worker.
func (unimplementedVgiService) CatalogSchemaContentsMacros(context.Context, *vgirpc.CallContext, CatalogSchemaContentsMacrosParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_schema_contents_macros")
}

// CatalogSchemaContentsTables answers UNIMPLEMENTED: vgi.v2
// catalog_schema_contents_tables is not implemented by this worker.
func (unimplementedVgiService) CatalogSchemaContentsTables(context.Context, *vgirpc.CallContext, CatalogSchemaContentsTablesParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_schema_contents_tables")
}

// CatalogSchemaContentsViews answers UNIMPLEMENTED: vgi.v2
// catalog_schema_contents_views is not implemented by this worker.
func (unimplementedVgiService) CatalogSchemaContentsViews(context.Context, *vgirpc.CallContext, CatalogSchemaContentsViewsParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_schema_contents_views")
}

// CatalogSchemaCreate answers UNIMPLEMENTED: vgi.v2 catalog_schema_create is
// not implemented by this worker.
func (unimplementedVgiService) CatalogSchemaCreate(context.Context, *vgirpc.CallContext, CatalogSchemaCreateParams) error {
	return methodNotImplemented("catalog_schema_create")
}

// CatalogSchemaDrop answers UNIMPLEMENTED: vgi.v2 catalog_schema_drop is not
// implemented by this worker.
func (unimplementedVgiService) CatalogSchemaDrop(context.Context, *vgirpc.CallContext, CatalogSchemaDropParams) error {
	return methodNotImplemented("catalog_schema_drop")
}

// CatalogSchemaGet answers UNIMPLEMENTED: vgi.v2 catalog_schema_get is not
// implemented by this worker.
func (unimplementedVgiService) CatalogSchemaGet(context.Context, *vgirpc.CallContext, CatalogSchemaGetParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_schema_get")
}

// CatalogSchemas answers UNIMPLEMENTED: vgi.v2 catalog_schemas is not
// implemented by this worker.
func (unimplementedVgiService) CatalogSchemas(context.Context, *vgirpc.CallContext, CatalogSchemasParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_schemas")
}

// CatalogTableColumnAdd answers UNIMPLEMENTED: vgi.v2 catalog_table_column_add
// is not implemented by this worker.
func (unimplementedVgiService) CatalogTableColumnAdd(context.Context, *vgirpc.CallContext, CatalogTableColumnAddParams) error {
	return methodNotImplemented("catalog_table_column_add")
}

// CatalogTableColumnCommentSet answers UNIMPLEMENTED: vgi.v2
// catalog_table_column_comment_set is not implemented by this worker.
func (unimplementedVgiService) CatalogTableColumnCommentSet(context.Context, *vgirpc.CallContext, CatalogTableColumnCommentSetParams) error {
	return methodNotImplemented("catalog_table_column_comment_set")
}

// CatalogTableColumnDefaultDrop answers UNIMPLEMENTED: vgi.v2
// catalog_table_column_default_drop is not implemented by this worker.
func (unimplementedVgiService) CatalogTableColumnDefaultDrop(context.Context, *vgirpc.CallContext, CatalogTableColumnDefaultDropParams) error {
	return methodNotImplemented("catalog_table_column_default_drop")
}

// CatalogTableColumnDefaultSet answers UNIMPLEMENTED: vgi.v2
// catalog_table_column_default_set is not implemented by this worker.
func (unimplementedVgiService) CatalogTableColumnDefaultSet(context.Context, *vgirpc.CallContext, CatalogTableColumnDefaultSetParams) error {
	return methodNotImplemented("catalog_table_column_default_set")
}

// CatalogTableColumnDrop answers UNIMPLEMENTED: vgi.v2
// catalog_table_column_drop is not implemented by this worker.
func (unimplementedVgiService) CatalogTableColumnDrop(context.Context, *vgirpc.CallContext, CatalogTableColumnDropParams) error {
	return methodNotImplemented("catalog_table_column_drop")
}

// CatalogTableColumnRename answers UNIMPLEMENTED: vgi.v2
// catalog_table_column_rename is not implemented by this worker.
func (unimplementedVgiService) CatalogTableColumnRename(context.Context, *vgirpc.CallContext, CatalogTableColumnRenameParams) error {
	return methodNotImplemented("catalog_table_column_rename")
}

// CatalogTableColumnStatisticsGet answers UNIMPLEMENTED: vgi.v2
// catalog_table_column_statistics_get is not implemented by this worker.
func (unimplementedVgiService) CatalogTableColumnStatisticsGet(context.Context, *vgirpc.CallContext, CatalogTableColumnStatisticsGetParams) (*[]byte, error) {
	return nil, methodNotImplemented("catalog_table_column_statistics_get")
}

// CatalogTableColumnTypeChange answers UNIMPLEMENTED: vgi.v2
// catalog_table_column_type_change is not implemented by this worker.
func (unimplementedVgiService) CatalogTableColumnTypeChange(context.Context, *vgirpc.CallContext, CatalogTableColumnTypeChangeParams) error {
	return methodNotImplemented("catalog_table_column_type_change")
}

// CatalogTableCommentSet answers UNIMPLEMENTED: vgi.v2
// catalog_table_comment_set is not implemented by this worker.
func (unimplementedVgiService) CatalogTableCommentSet(context.Context, *vgirpc.CallContext, CatalogTableCommentSetParams) error {
	return methodNotImplemented("catalog_table_comment_set")
}

// CatalogTableCreate answers UNIMPLEMENTED: vgi.v2 catalog_table_create is not
// implemented by this worker.
func (unimplementedVgiService) CatalogTableCreate(context.Context, *vgirpc.CallContext, TableCreateRequestWire) error {
	return methodNotImplemented("catalog_table_create")
}

// CatalogTableDeleteFunctionGet answers UNIMPLEMENTED: vgi.v2
// catalog_table_delete_function_get is not implemented by this worker.
func (unimplementedVgiService) CatalogTableDeleteFunctionGet(context.Context, *vgirpc.CallContext, CatalogTableDeleteFunctionGetParams) (TableScanFunctionGetResponseWire, error) {
	return TableScanFunctionGetResponseWire{}, methodNotImplemented("catalog_table_delete_function_get")
}

// CatalogTableDrop answers UNIMPLEMENTED: vgi.v2 catalog_table_drop is not
// implemented by this worker.
func (unimplementedVgiService) CatalogTableDrop(context.Context, *vgirpc.CallContext, CatalogTableDropParams) error {
	return methodNotImplemented("catalog_table_drop")
}

// CatalogTableGet answers UNIMPLEMENTED: vgi.v2 catalog_table_get is not
// implemented by this worker.
func (unimplementedVgiService) CatalogTableGet(context.Context, *vgirpc.CallContext, CatalogTableGetParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_table_get")
}

// CatalogTableInsertFunctionGet answers UNIMPLEMENTED: vgi.v2
// catalog_table_insert_function_get is not implemented by this worker.
func (unimplementedVgiService) CatalogTableInsertFunctionGet(context.Context, *vgirpc.CallContext, CatalogTableInsertFunctionGetParams) (TableScanFunctionGetResponseWire, error) {
	return TableScanFunctionGetResponseWire{}, methodNotImplemented("catalog_table_insert_function_get")
}

// CatalogTableNotNullDrop answers UNIMPLEMENTED: vgi.v2
// catalog_table_not_null_drop is not implemented by this worker.
func (unimplementedVgiService) CatalogTableNotNullDrop(context.Context, *vgirpc.CallContext, CatalogTableNotNullDropParams) error {
	return methodNotImplemented("catalog_table_not_null_drop")
}

// CatalogTableNotNullSet answers UNIMPLEMENTED: vgi.v2
// catalog_table_not_null_set is not implemented by this worker.
func (unimplementedVgiService) CatalogTableNotNullSet(context.Context, *vgirpc.CallContext, CatalogTableNotNullSetParams) error {
	return methodNotImplemented("catalog_table_not_null_set")
}

// CatalogTableRename answers UNIMPLEMENTED: vgi.v2 catalog_table_rename is not
// implemented by this worker.
func (unimplementedVgiService) CatalogTableRename(context.Context, *vgirpc.CallContext, CatalogTableRenameParams) error {
	return methodNotImplemented("catalog_table_rename")
}

// CatalogTableScanBranchesGet answers UNIMPLEMENTED: vgi.v2
// catalog_table_scan_branches_get is not implemented by this worker.
func (unimplementedVgiService) CatalogTableScanBranchesGet(context.Context, *vgirpc.CallContext, CatalogTableScanBranchesGetParams) (TableScanBranchesGetResponseWire, error) {
	return TableScanBranchesGetResponseWire{}, methodNotImplemented("catalog_table_scan_branches_get")
}

// CatalogTableScanFunctionGet answers UNIMPLEMENTED: vgi.v2
// catalog_table_scan_function_get is not implemented by this worker.
func (unimplementedVgiService) CatalogTableScanFunctionGet(context.Context, *vgirpc.CallContext, CatalogTableScanFunctionGetParams) (TableScanFunctionGetResponseWire, error) {
	return TableScanFunctionGetResponseWire{}, methodNotImplemented("catalog_table_scan_function_get")
}

// CatalogTableUpdateFunctionGet answers UNIMPLEMENTED: vgi.v2
// catalog_table_update_function_get is not implemented by this worker.
func (unimplementedVgiService) CatalogTableUpdateFunctionGet(context.Context, *vgirpc.CallContext, CatalogTableUpdateFunctionGetParams) (TableScanFunctionGetResponseWire, error) {
	return TableScanFunctionGetResponseWire{}, methodNotImplemented("catalog_table_update_function_get")
}

// CatalogTransactionBegin answers UNIMPLEMENTED: vgi.v2
// catalog_transaction_begin is not implemented by this worker.
func (unimplementedVgiService) CatalogTransactionBegin(context.Context, *vgirpc.CallContext, CatalogTransactionBeginParams) (TransactionBeginResponseWire, error) {
	return TransactionBeginResponseWire{}, methodNotImplemented("catalog_transaction_begin")
}

// CatalogTransactionCommit answers UNIMPLEMENTED: vgi.v2
// catalog_transaction_commit is not implemented by this worker.
func (unimplementedVgiService) CatalogTransactionCommit(context.Context, *vgirpc.CallContext, CatalogTransactionCommitParams) error {
	return methodNotImplemented("catalog_transaction_commit")
}

// CatalogTransactionRollback answers UNIMPLEMENTED: vgi.v2
// catalog_transaction_rollback is not implemented by this worker.
func (unimplementedVgiService) CatalogTransactionRollback(context.Context, *vgirpc.CallContext, CatalogTransactionRollbackParams) error {
	return methodNotImplemented("catalog_transaction_rollback")
}

// CatalogVersion answers UNIMPLEMENTED: vgi.v2 catalog_version is not
// implemented by this worker.
func (unimplementedVgiService) CatalogVersion(context.Context, *vgirpc.CallContext, CatalogVersionParams) (CatalogVersionResponseWire, error) {
	return CatalogVersionResponseWire{}, methodNotImplemented("catalog_version")
}

// CatalogViewCommentSet answers UNIMPLEMENTED: vgi.v2 catalog_view_comment_set
// is not implemented by this worker.
func (unimplementedVgiService) CatalogViewCommentSet(context.Context, *vgirpc.CallContext, CatalogViewCommentSetParams) error {
	return methodNotImplemented("catalog_view_comment_set")
}

// CatalogViewCreate answers UNIMPLEMENTED: vgi.v2 catalog_view_create is not
// implemented by this worker.
func (unimplementedVgiService) CatalogViewCreate(context.Context, *vgirpc.CallContext, CatalogViewCreateParams) error {
	return methodNotImplemented("catalog_view_create")
}

// CatalogViewDrop answers UNIMPLEMENTED: vgi.v2 catalog_view_drop is not
// implemented by this worker.
func (unimplementedVgiService) CatalogViewDrop(context.Context, *vgirpc.CallContext, CatalogViewDropParams) error {
	return methodNotImplemented("catalog_view_drop")
}

// CatalogViewGet answers UNIMPLEMENTED: vgi.v2 catalog_view_get is not
// implemented by this worker.
func (unimplementedVgiService) CatalogViewGet(context.Context, *vgirpc.CallContext, CatalogViewGetParams) (ItemsResponseWire, error) {
	return ItemsResponseWire{}, methodNotImplemented("catalog_view_get")
}

// CatalogViewRename answers UNIMPLEMENTED: vgi.v2 catalog_view_rename is not
// implemented by this worker.
func (unimplementedVgiService) CatalogViewRename(context.Context, *vgirpc.CallContext, CatalogViewRenameParams) error {
	return methodNotImplemented("catalog_view_rename")
}

// Init answers UNIMPLEMENTED: vgi.v2 init is not implemented by this worker.
func (unimplementedVgiService) Init(context.Context, *vgirpc.CallContext, InitRequestWire) (*vgirpc.StreamResult, error) {
	return nil, methodNotImplemented("init")
}

// TableBufferingCombine answers UNIMPLEMENTED: vgi.v2 table_buffering_combine
// is not implemented by this worker.
func (unimplementedVgiService) TableBufferingCombine(context.Context, *vgirpc.CallContext, TableBufferingCombineRequestWire) (TableBufferingCombineResponseWire, error) {
	return TableBufferingCombineResponseWire{}, methodNotImplemented("table_buffering_combine")
}

// TableBufferingDestructor answers UNIMPLEMENTED: vgi.v2
// table_buffering_destructor is not implemented by this worker.
func (unimplementedVgiService) TableBufferingDestructor(context.Context, *vgirpc.CallContext, TableBufferingDestructorRequestWire) (TableBufferingDestructorResponseWire, error) {
	return TableBufferingDestructorResponseWire{}, methodNotImplemented("table_buffering_destructor")
}

// TableBufferingProcess answers UNIMPLEMENTED: vgi.v2 table_buffering_process
// is not implemented by this worker.
func (unimplementedVgiService) TableBufferingProcess(context.Context, *vgirpc.CallContext, TableBufferingProcessRequestWire) (TableBufferingProcessResponseWire, error) {
	return TableBufferingProcessResponseWire{}, methodNotImplemented("table_buffering_process")
}

// TableFunctionCardinality answers UNIMPLEMENTED: vgi.v2
// table_function_cardinality is not implemented by this worker.
func (unimplementedVgiService) TableFunctionCardinality(context.Context, *vgirpc.CallContext, CardinalityRequestWire) (TableCardinality, error) {
	return TableCardinality{}, methodNotImplemented("table_function_cardinality")
}

// TableFunctionDynamicToString answers UNIMPLEMENTED: vgi.v2
// table_function_dynamic_to_string is not implemented by this worker.
func (unimplementedVgiService) TableFunctionDynamicToString(context.Context, *vgirpc.CallContext, TableFunctionDynamicToStringRequestWire) (TableFunctionDynamicToStringResponseWire, error) {
	return TableFunctionDynamicToStringResponseWire{}, methodNotImplemented("table_function_dynamic_to_string")
}

// TableFunctionPlan answers UNIMPLEMENTED: vgi.v2 table_function_plan is not
// implemented by this worker.
func (unimplementedVgiService) TableFunctionPlan(context.Context, *vgirpc.CallContext, PlanRequestWire) (PlanResponseWire, error) {
	return PlanResponseWire{}, methodNotImplemented("table_function_plan")
}

// TableFunctionStatistics answers UNIMPLEMENTED: vgi.v2
// table_function_statistics is not implemented by this worker.
func (unimplementedVgiService) TableFunctionStatistics(context.Context, *vgirpc.CallContext, CardinalityRequestWire) (*[]byte, error) {
	return nil, methodNotImplemented("table_function_statistics")
}

// registerVgiService hosts every vgi.v2 method on s, each dispatched to svc.
// The table is the protocol's whole method set: a method svc does not
// implement still registers, and answers UNIMPLEMENTED.
func registerVgiService(w *Worker, s *vgirpc.Server, svc vgiService) {
	registerVgiCatalogMethods(w, s, svc)
	vgirpc.Unary[AggregateBindRequestWire, AggregateBindResponseWire](s, "aggregate_bind", svc.AggregateBind)
	vgirpc.Unary[AggregateCombineRequestWire, AggregateCombineResponseWire](s, "aggregate_combine", svc.AggregateCombine)
	vgirpc.Unary[AggregateDestructorRequestWire, AggregateDestructorResponseWire](s, "aggregate_destructor", svc.AggregateDestructor)
	vgirpc.Unary[AggregateFinalizeRequestWire, AggregateFinalizeResponseWire](s, "aggregate_finalize", svc.AggregateFinalize)
	vgirpc.Unary[AggregateStreamingChunkRequestWire, AggregateStreamingChunkResponseWire](s, "aggregate_streaming_chunk", svc.AggregateStreamingChunk)
	vgirpc.Unary[AggregateStreamingCloseRequestWire, AggregateStreamingCloseResponseWire](s, "aggregate_streaming_close", svc.AggregateStreamingClose)
	vgirpc.Unary[AggregateStreamingOpenRequestWire, AggregateStreamingOpenResponseWire](s, "aggregate_streaming_open", svc.AggregateStreamingOpen)
	vgirpc.Unary[AggregateUpdateRequestWire, AggregateUpdateResponseWire](s, "aggregate_update", svc.AggregateUpdate)
	vgirpc.Unary[AggregateWindowRequestWire, AggregateWindowResponseWire](s, "aggregate_window", svc.AggregateWindow)
	vgirpc.Unary[AggregateWindowBatchRequestWire, AggregateWindowBatchResponseWire](s, "aggregate_window_batch", svc.AggregateWindowBatch)
	vgirpc.Unary[AggregateWindowDestructorRequestWire, AggregateWindowDestructorResponseWire](s, "aggregate_window_destructor", svc.AggregateWindowDestructor)
	vgirpc.Unary[AggregateWindowInitRequestWire, AggregateWindowInitResponseWire](s, "aggregate_window_init", svc.AggregateWindowInit)
	vgirpc.Unary[BindRequestWire, BindResponseWire](s, "bind", svc.Bind)
	vgirpc.DynamicStreamWithHeader[InitRequestWire](s, "init", vgiInitHeaderSchema, svc.Init)
	vgirpc.Unary[TableBufferingCombineRequestWire, TableBufferingCombineResponseWire](s, "table_buffering_combine", svc.TableBufferingCombine)
	vgirpc.Unary[TableBufferingDestructorRequestWire, TableBufferingDestructorResponseWire](s, "table_buffering_destructor", svc.TableBufferingDestructor)
	vgirpc.Unary[TableBufferingProcessRequestWire, TableBufferingProcessResponseWire](s, "table_buffering_process", svc.TableBufferingProcess)
	vgirpc.Unary[CardinalityRequestWire, TableCardinality](s, "table_function_cardinality", svc.TableFunctionCardinality)
	vgirpc.Unary[TableFunctionDynamicToStringRequestWire, TableFunctionDynamicToStringResponseWire](s, "table_function_dynamic_to_string", svc.TableFunctionDynamicToString)
	vgirpc.Unary[PlanRequestWire, PlanResponseWire](s, "table_function_plan", svc.TableFunctionPlan)
	vgirpc.Unary[CardinalityRequestWire, *[]byte](s, "table_function_statistics", svc.TableFunctionStatistics)
}

// registerVgiCatalogMethods hosts the catalog_* methods through unaryCatalog /
// unaryVoidCatalog, which unseal opaque values and route an attach to the
// catalog that owns it. With a nil s it only records them, for a sub-catalog.
func registerVgiCatalogMethods(w *Worker, s *vgirpc.Server, svc vgiService) {
	unaryCatalog[CatalogAttachRequestWire, generated.CatalogAttachResult](w, s, "catalog_attach", svc.CatalogAttach)
	unaryCatalog[CatalogCatalogsParams, CatalogsResponseWire](w, s, "catalog_catalogs", svc.CatalogCatalogs)
	unaryCatalog[CatalogContentsParams, generated.CatalogContentsResponse](w, s, "catalog_contents", svc.CatalogContents)
	unaryCatalog[CatalogCopyFromFormatsParams, ItemsResponseWire](w, s, "catalog_copy_from_formats", svc.CatalogCopyFromFormats)
	unaryVoidCatalog[CatalogCreateRequestWire](w, s, "catalog_create", svc.CatalogCreate)
	unaryVoidCatalog[CatalogDetachParams](w, s, "catalog_detach", svc.CatalogDetach)
	unaryVoidCatalog[CatalogDropParams](w, s, "catalog_drop", svc.CatalogDrop)
	unaryVoidCatalog[IndexCreateRequestWire](w, s, "catalog_index_create", svc.CatalogIndexCreate)
	unaryVoidCatalog[CatalogIndexDropParams](w, s, "catalog_index_drop", svc.CatalogIndexDrop)
	unaryCatalog[CatalogIndexGetParams, ItemsResponseWire](w, s, "catalog_index_get", svc.CatalogIndexGet)
	unaryVoidCatalog[MacroCreateRequestWire](w, s, "catalog_macro_create", svc.CatalogMacroCreate)
	unaryVoidCatalog[CatalogMacroDropParams](w, s, "catalog_macro_drop", svc.CatalogMacroDrop)
	unaryCatalog[CatalogMacroGetParams, ItemsResponseWire](w, s, "catalog_macro_get", svc.CatalogMacroGet)
	unaryCatalog[CatalogSchemaContentsFunctionsParams, ItemsResponseWire](w, s, "catalog_schema_contents_functions", svc.CatalogSchemaContentsFunctions)
	unaryCatalog[CatalogSchemaContentsIndexesParams, ItemsResponseWire](w, s, "catalog_schema_contents_indexes", svc.CatalogSchemaContentsIndexes)
	unaryCatalog[CatalogSchemaContentsMacrosParams, ItemsResponseWire](w, s, "catalog_schema_contents_macros", svc.CatalogSchemaContentsMacros)
	unaryCatalog[CatalogSchemaContentsTablesParams, ItemsResponseWire](w, s, "catalog_schema_contents_tables", svc.CatalogSchemaContentsTables)
	unaryCatalog[CatalogSchemaContentsViewsParams, ItemsResponseWire](w, s, "catalog_schema_contents_views", svc.CatalogSchemaContentsViews)
	unaryVoidCatalog[CatalogSchemaCreateParams](w, s, "catalog_schema_create", svc.CatalogSchemaCreate)
	unaryVoidCatalog[CatalogSchemaDropParams](w, s, "catalog_schema_drop", svc.CatalogSchemaDrop)
	unaryCatalog[CatalogSchemaGetParams, ItemsResponseWire](w, s, "catalog_schema_get", svc.CatalogSchemaGet)
	unaryCatalog[CatalogSchemasParams, ItemsResponseWire](w, s, "catalog_schemas", svc.CatalogSchemas)
	unaryVoidCatalog[CatalogTableColumnAddParams](w, s, "catalog_table_column_add", svc.CatalogTableColumnAdd)
	unaryVoidCatalog[CatalogTableColumnCommentSetParams](w, s, "catalog_table_column_comment_set", svc.CatalogTableColumnCommentSet)
	unaryVoidCatalog[CatalogTableColumnDefaultDropParams](w, s, "catalog_table_column_default_drop", svc.CatalogTableColumnDefaultDrop)
	unaryVoidCatalog[CatalogTableColumnDefaultSetParams](w, s, "catalog_table_column_default_set", svc.CatalogTableColumnDefaultSet)
	unaryVoidCatalog[CatalogTableColumnDropParams](w, s, "catalog_table_column_drop", svc.CatalogTableColumnDrop)
	unaryVoidCatalog[CatalogTableColumnRenameParams](w, s, "catalog_table_column_rename", svc.CatalogTableColumnRename)
	unaryCatalog[CatalogTableColumnStatisticsGetParams, *[]byte](w, s, "catalog_table_column_statistics_get", svc.CatalogTableColumnStatisticsGet)
	unaryVoidCatalog[CatalogTableColumnTypeChangeParams](w, s, "catalog_table_column_type_change", svc.CatalogTableColumnTypeChange)
	unaryVoidCatalog[CatalogTableCommentSetParams](w, s, "catalog_table_comment_set", svc.CatalogTableCommentSet)
	unaryVoidCatalog[TableCreateRequestWire](w, s, "catalog_table_create", svc.CatalogTableCreate)
	unaryCatalog[CatalogTableDeleteFunctionGetParams, TableScanFunctionGetResponseWire](w, s, "catalog_table_delete_function_get", svc.CatalogTableDeleteFunctionGet)
	unaryVoidCatalog[CatalogTableDropParams](w, s, "catalog_table_drop", svc.CatalogTableDrop)
	unaryCatalog[CatalogTableGetParams, ItemsResponseWire](w, s, "catalog_table_get", svc.CatalogTableGet)
	unaryCatalog[CatalogTableInsertFunctionGetParams, TableScanFunctionGetResponseWire](w, s, "catalog_table_insert_function_get", svc.CatalogTableInsertFunctionGet)
	unaryVoidCatalog[CatalogTableNotNullDropParams](w, s, "catalog_table_not_null_drop", svc.CatalogTableNotNullDrop)
	unaryVoidCatalog[CatalogTableNotNullSetParams](w, s, "catalog_table_not_null_set", svc.CatalogTableNotNullSet)
	unaryVoidCatalog[CatalogTableRenameParams](w, s, "catalog_table_rename", svc.CatalogTableRename)
	unaryCatalog[CatalogTableScanBranchesGetParams, TableScanBranchesGetResponseWire](w, s, "catalog_table_scan_branches_get", svc.CatalogTableScanBranchesGet)
	unaryCatalog[CatalogTableScanFunctionGetParams, TableScanFunctionGetResponseWire](w, s, "catalog_table_scan_function_get", svc.CatalogTableScanFunctionGet)
	unaryCatalog[CatalogTableUpdateFunctionGetParams, TableScanFunctionGetResponseWire](w, s, "catalog_table_update_function_get", svc.CatalogTableUpdateFunctionGet)
	unaryCatalog[CatalogTransactionBeginParams, TransactionBeginResponseWire](w, s, "catalog_transaction_begin", svc.CatalogTransactionBegin)
	unaryVoidCatalog[CatalogTransactionCommitParams](w, s, "catalog_transaction_commit", svc.CatalogTransactionCommit)
	unaryVoidCatalog[CatalogTransactionRollbackParams](w, s, "catalog_transaction_rollback", svc.CatalogTransactionRollback)
	unaryCatalog[CatalogVersionParams, CatalogVersionResponseWire](w, s, "catalog_version", svc.CatalogVersion)
	unaryVoidCatalog[CatalogViewCommentSetParams](w, s, "catalog_view_comment_set", svc.CatalogViewCommentSet)
	unaryVoidCatalog[CatalogViewCreateParams](w, s, "catalog_view_create", svc.CatalogViewCreate)
	unaryVoidCatalog[CatalogViewDropParams](w, s, "catalog_view_drop", svc.CatalogViewDrop)
	unaryCatalog[CatalogViewGetParams, ItemsResponseWire](w, s, "catalog_view_get", svc.CatalogViewGet)
	unaryVoidCatalog[CatalogViewRenameParams](w, s, "catalog_view_rename", svc.CatalogViewRename)
}
